[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:test"
healthcheckPath = "/test"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
port = 3000
healthcheckInterval = 30

[[services]]
name = "bookmark-manager-backend"
