[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[[services]]
name = "bookmark-manager-backend"
